services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_service
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgress:
    image: postgres:latest
    container_name: postgress_service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: users
    volumes:
      - postgres-data:/var/lib/postgresql/data      

volumes:
  mongo-data:
  postgres-data:
